a)

In [1]:
import pint

units = pint.UnitRegistry()

G = 6.674e-11 * units.meter**3 / (units.kilogram * units.second**2)
c = 2.998e8 * units.meter / units.second
M_sun = 1.989e30 * units.kilogram

def Schwarzschild_Radius(M):
    R_s = (2 * G * M) / c**2
    return R_s

print(f"The Schwarzschild radius of the Sun is {Schwarzschild_Radius(M_sun).to(units.meter):.2f}")


The Schwarzschild radius of the Sun is 2953.85 meter


b)

In [2]:
import numpy as np

#Nested loop
def nested(A,B):
    rows_A,cols_A=np.shape(A)
    rows_B,cols_B=np.shape(B)
    
    result=[]
    for i in range(rows_A):
        result.append([0]*cols_B)
    
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j]+=A[i][k]*B[k][j]
    return result


#list comprehension
def list_comp(A, B):
    transB=list(zip(*B))
    return [[sum(x*y for x,y in zip(i,j)) for j in transB] for i in A]


#numpy
def npy(A, B):
    A_np = np.array(A)
    B_np = np.array(B)
    return np.dot(A_np, B_np)

matrix1 = np.random.randint(0, 10, size=(3, 3))
matrix2 = np.random.randint(0, 10, size=(3, 3))

print(nested(matrix1,matrix2),'\n',list_comp(matrix1,matrix2),'\n',npy(matrix1,matrix2))

[[9, 63, 54], [8, 40, 72], [21, 74, 84]] 
 [[9, 63, 54], [8, 40, 72], [21, 74, 84]] 
 [[ 9 63 54]
 [ 8 40 72]
 [21 74 84]]


c)

In [3]:
import time

def benchmark(multiply_func, runs=10, size=100):
    times = []

    for _ in range(runs):
        matrix1 = np.random.randint(0, 10, size=(size, size))
        matrix2 = np.linalg.inv(matrix1)

        start = time.time()
        multiply_func(matrix1, matrix2)
        end = time.time()
        times.append(end - start)

    mean_time = np.mean(times)
    std_time = np.std(times)

    return mean_time, std_time

mean_nested, std_nested = benchmark(nested, runs=10, size=100)
mean_list_comp, std_list_comp = benchmark(list_comp, runs=10, size=100)
mean_npy, std_npy = benchmark(npy, runs=10, size=100)

print(f"Nested loop - Mean time: {mean_nested:.6f} s, Standard Deviation: {std_nested:.6f}")
print(f"List comprehension - Mean time: {mean_list_comp:.6f} s, Standard Deviation: {std_list_comp:.6f}")
print(f"NumPy - Mean time: {mean_npy:.6f} s, Standard Deviation: {std_npy:.6f}")

Nested loop - Mean time: 0.844403 s, Standard Deviation: 0.045546
List comprehension - Mean time: 0.423700 s, Standard Deviation: 0.026283
NumPy - Mean time: 0.000099 s, Standard Deviation: 0.000296
